name: "[CD] Continuous Delivery"

# Sempre que tiver um commit ou um PR for aberto
# on:
#   push:
#     branches: [ main ]
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [ main ]

env:
  VERCEL_ORG_ID: xZMpNRA1x2PlRSa1dCL8x9uI
  VERCEL_PROJECT_ID: prj_Qbd1PpK6gHor5wKdutdUuKVrQY7z

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Debug"
        run: |
          ls -la
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Deploy"
        run: "npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}"
  